### ISSUE TITLE
App crashes on startup due to missing backend urls (leads to uncaught okhttp exception)

### ISSUE THREAD

**Issue by IndianaDschones** [corona-warn-app/cwa-app-android#237]
## Describe the bug

The app built from https://github.com/corona-warn-app/cwa-app-android/commit/16f016a99b971d89e9f4c988c4ce8f7421f9983d crashes on startup.

## Expected behaviour
It should not crash and instead show some kind of error message.

## Steps to reproduce the issue

Build and run the app from commit https://github.com/corona-warn-app/cwa-app-android/commit/16f016a99b971d89e9f4c988c4ce8f7421f9983d

## Technical details
n/A

## Possible Fix

The reason for this crash are the missing backend URLs. OkHTTP is expecting valid URLs starting with `http://` or `https://`. Since the update check is invoked on startup, the app crashes immediately.

However, the uncaught exception is the _real_ reason for the crash.

## Additional context
Excerpt from Logcat:
`java.lang.ExceptionInInitializerError
at de.rki.coronawarnapp.service.applicationconfiguration.ApplicationConfigurationService.asyncRetrieveApplicationConfiguration(ApplicationConfigurationService.kt:9)
        at de.rki.coronawarnapp.update.UpdateChecker.checkIfUpdatesNeededFromServer(UpdateChecker.kt:122)
        at de.rki.coronawarnapp.update.UpdateChecker.checkForUpdate(UpdateChecker.kt:35
`
[...]
`Caused by: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
        at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1260)`

**Comment by jakobmoellersap** [comment]
Resolved in latest Dev
