### ISSUE TITLE
Error 9002 - "Connection reset." appears once per day.

### ISSUE THREAD

**Issue by sfadschm** [corona-warn-app/cwa-app-android#2953]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ]
* [x] Bug is specific for Android
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3a
- Android version: 11
- App version: 2.0.4

## Describe the bug
When opening the app for the first time of the day, the error 9002 "Connection reset" occurs.
This error only occurs since the 2.0.4 update but is reproducible every day. It is only triggered when opening the app for the first time.
I tried triggering it by switching from WLAN to LTE during daytime, resetting our Router connection, turning the phone off and on, but did not have any success.

As far as I can tell, functionality of the app is not touched by this, as after confirming the error, contacts get checked like normally.

## Steps to reproduce the issue
![Screenshot_20210425-094951](https://user-images.githubusercontent.com/40514119/115985435-26de6880-a5ac-11eb-9fb1-1c70b733b99f.png)
![Screenshot_20210425-081521](https://user-images.githubusercontent.com/40514119/115985447-2c3bb300-a5ac-11eb-8b72-3034452db74e.png)

1. Have CWA App closed overnight.
2. Wake up in the morning.
3. Open CWA App.
4. Get error.

## Expected behaviour
The App opens without any error.

**Comment by dsarkar** [comment]
@sfadschm Tanks for reporting. We created an Internal Tracking ID: [EXPOSUREAPP-6714](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6714). The development team will have a look at this issue. Any further news regarding this issue will be published here. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by schuhmi2** [comment]
Ditto, I'm experiencing this too
OnePlus 6T android 10
CoronaWarn app v 2.0.4

**Comment by sfadschm** [comment]
Addition:
Just got the same error a second time today.
Still cannot trigger it intentionally.

**Comment by MikeMcC399** [comment]
This issue is listed in the resolved section of the FAQs https://www.coronawarn.app/en/faq/#cause9002_timeout which refers also to issue https://github.com/corona-warn-app/cwa-app-android/issues/998.

I have seen it occurring sporadically on an emulated Google Pixel 3a device using Android 11. Emulators are generally slower than real physical devices, so this would be consistent with a timeout issue.

**Comment by sfadschm** [comment]
Not sure this is the same issue. From the GitHub issue list, it seems error 9002 can have multiple causes. This here os "Connection reset." Not sure its the same as "timeout".

**Comment by MikeMcC399** [comment]
@sfadschm 
> Not sure this is the same issue. From the GitHub issue list, it seems error 9002 can have multiple causes. This here is "Connection reset". Not sure its the same as "timeout".

Thanks for pointing this out. 
You're right that error 9002 can cover many reasons:
https://github.com/corona-warn-app/cwa-app-android/blob/f65f66f7e84517cfb12f67b0b6b7ad05d86c8b24/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ErrorCodes.kt#L19

In the case of the timeout issue #998 the stack trace is showing
`java.net.SocketTimeoutException: timeout`

whereas your stack trace from this issue (#2953) shows
`java.net.SocketException: Connection reset`

There may be a relationship between the two, but we probably need the help of the developers to troubleshoot further. I did try again today to see if I could reproduce, but as it happens I'm not getting any error.

**Comment by holgel** [comment]
With me it also occurs sporadically during startup.
I had generated a QR code after the update to 2.0.4, logged into this event and logged out again. The next time I restarted, the above-mentioned problem occurred.

Stack trace:

java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:139)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:5)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:21)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:1)
	at org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:7)
	at org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:10)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:30)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:27)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:113)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:20)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:222)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:36)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:35)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
	at de.rki.coronawarnapp.http.HttpErrorParser.intercept(HttpErrorParser.kt:1)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
	at de.rki.coronawarnapp.http.interceptor.RetryInterceptor.intercept(RetryInterceptor.kt:2)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:4)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
	at de.rki.coronawarnapp.http.interceptor.WebSecurityVerificationInterceptor.intercept(WebSecurityVerificationInterceptor.kt:1)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:25)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:12)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

**Comment by d4rken** [comment]
Thanks for the stacktrace in text form :grin: 

My current theory is that the error orginates from:
https://github.com/corona-warn-app/cwa-app-android/blob/e1ec946e09600826d16ea389aa8dd96f7c959129/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/server/DiagnosisKeyServer.kt#L31-L38

It should not have a relation with CheckIns, I don't know yet why this suddenly occurs.

**Comment by holgel** [comment]
In any case, the time factor plays a role. If I wait a certain amount of time (about 3h I tried) before restarting the app after the last crash, the error comes back, otherwise it starts normally.

**Comment by d4rken** [comment]
Did anyone have a registered test when the error showed?

**Comment by sfadschm** [comment]
> Did anyone have a registered test when the error showed?

Now that you mention it: yes!
It was an old one and it expired yesterday so it was deleted. Today I did not get the error yet.

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/2973

**Comment by schuhmi2** [comment]
> Did anyone have a registered test when the error showed?

Yeh, I did have an old one too that just expired. Upon deleting it, I too did not get this error this morning.

**Comment by d4rken** [comment]
@dsarkar #2973 is not a fix for the connection reset error. That likely can't be fixed on client side. Maybe hidden, but without any other error reporting, just hiding it is also not great.

#2973 fixes EXPOSUREAPP-6784, it will prevent the connection reset error from causing the "test invalid" card to display which could cause the user to remove actually valid test.

We should leave this ticket open for other users to find it until either server side the error is fixed, or a decision was made to hide the error popup for this case type of error.

**Comment by holgel** [comment]
> Did anyone have a registered test when the error showed?

I also have an expired test that I have not yet deleted.

**Comment by holgel** [comment]
> > I also have an expired test that I have not yet deleted.
> 
> Do you still get the error?

No, the error does not seem to occur anymore.

**Comment by MikeMcC399** [comment]
I have been trying to reproduce this error on an Android 8 device with a dummy test registered, but so far, no error message. I tried for instance disabling WiFi for more than 4 hours (with no mobile data enabled either), then starting CWA before and after WiFi was reenabled. 

Sidenote: [CWA Android 2.0.5](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.0.5) has been released and I have installed it from the [Google Play Store](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp).
