### ISSUE TITLE
Scanning both vaccination certificates results in VC_NAME_MISSMATCH

### ISSUE THREAD

**Issue by deepred-dev** [corona-warn-app/cwa-app-android#3434]
## Avoid duplicates
* [X ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung S10 SM-G973F
- Android version: 11
- App version: 2.3.4

## Describe the bug
For both vaccination, an individual certificate with an unique barcode is issues. The instructions on the certificate prints suggest to scan them both. This results in an VC_NAME_MISSMATCH error.

Apparently scanning the certificate of the second vaccination is sufficient. So if this error emerges, one has to delete the certificate of the first vaccination, and scan the second one. Then it is imported and states the full vaccination protection.
This error message is misleading and will probably cause a lot of confusion.
And after all, it makes no sense to issue two individual certificates, and then just offer the functionality to add only one.

By the way, the CovPass-App  is capable of adding both vaccination certificates without any problems. 

Stacktrace:
de.rki.coronawarnapp.vaccination.core.certificate.InvalidHealthCertificateException: Name does not match.
de.rki.coronawarnapp.vaccination.core.certificate.InvalidHealthCertificateException: Name does not match.
at de.rki.coronawarnapp.vaccination.core.repository.VaccinationRepository$registerVaccination$updatedData$1.invokeSuspend(VaccinationRepository.kt:28)
at de.rki.coronawarnapp.vaccination.core.repository.VaccinationRepository$registerVaccination$updatedData$1.invoke(VaccinationRepository.kt:2)
at de.rki.coronawarnapp.util.flow.HotDataFlow$internalProducer$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:13)
at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt:11)
at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:12)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:12)

## Steps to reproduce the issue

1. Go to Add Vaccination Certificate
2. Then scan the barcodes for vaccination 1
3. Then scan the barcodes for vaccination 2
5. 
![Screenshot_20210614-141211_Corona-Warn](https://user-images.githubusercontent.com/67878078/121893748-a1ab4080-cd1e-11eb-836b-63fac3dab18d.jpg)

## Expected behaviour

It should be possible to import the vaccination certificate for vaccination 1 and 2.

**Comment by thomasaugsten** [comment]
The names of both certificates needs to be the same. You have certificates with different name.

**Comment by deepred-dev** [comment]
> 
> 
> The names of both certificates needs to be the same. You have certificates with different name.

**Comment by deepred-dev** [comment]
Gee, you're right. On one of the certificates, they switched surname and forename. The certificates itself was wrongly issued
