### ISSUE TITLE
Problem generating EU certificate

### ISSUE THREAD

**Issue by darkdragon-001** [corona-warn-app/cwa-app-android#3924]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Xiaomi Mi A1
- Android version:
- App version: latest

## Describe the bug

After successfully showing a test result in the app, I get an error requesting a EU certificate:

<details><pre>
de.rki.coronawarnapp.covidcertificate.common.exception.InvalidHealthCertificateException: Json schema invalid.

de.rki.coronawarnapp.covidcertificate.common.exception.InvalidHealthCertificateException: Json schema invalid.
	at de.rki.coronawarnapp.covidcertificate.common.certificate.DccV1Parser.checkSchema(DccV1Parser.kt:10)
	at de.rki.coronawarnapp.covidcertificate.common.certificate.DccV1Parser.parse(DccV1Parser.kt:9)
	at de.rki.coronawarnapp.covidcertificate.common.certificate.DccQrCodeExtractor.parse(DccQrCodeExtractor.kt:7)
	at de.rki.coronawarnapp.covidcertificate.common.certificate.DccQrCodeExtractor.extract(DccQrCodeExtractor.kt:13)
	at de.rki.coronawarnapp.covidcertificate.test.core.TestCertificateProcessor.obtainCertificate$Corona_Warn_App_deviceRelease(TestCertificateProcessor.kt:55)
	at de.rki.coronawarnapp.covidcertificate.test.core.TestCertificateProcessor$obtainCertificate$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:11)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:3)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
Caused by: java.lang.IllegalArgumentException: Schema Validation did not pass:
$.t[0].tc: may only be 50 characters long
	at de.rki.coronawarnapp.covidcertificate.common.certificate.DccV1Parser.checkSchema(DccV1Parser.kt:9)
	... 12 more
</pre></details>

## Steps to reproduce the issue

Add test result via link and request EU certificate.

## Expected behaviour

Works without error.

## Possible Fix

Either fix your parser/validator or fix QR code / link generator.

**Comment by vaubaehn** [comment]
Hi, could you please provide as much details as possible, where you made the test?
Testcenter name, city, date

Looks like there is a problem with the software implementation of the test provider, that TSI did not check before granting the test provider access to their backend...

ping @thomasaugsten @daniel-eder

**Comment by vaubaehn** [comment]
@daniel-eder 
I pinged you, because I'm a bit concerned about QA, see also here: https://github.com/corona-warn-app/cwa-app-android/issues/3850#issuecomment-896904172

**Comment by vaubaehn** [comment]
@dsarkar @heinezen 
Additional info for the ticket:
It looks like the test provider used DCC schema 1.3.0, while CWA seems to check technical validity for schema v1.0.0, according to that line in the exception:
```
Caused by: java.lang.IllegalArgumentException: Schema Validation did not pass:
$.t[0].tc: may only be 50 characters long
at de.rki.coronawarnapp.covidcertificate.common.certificate.DccV1Parser.checkSchema(DccV1Parser.kt:9)
```

For the differences in the schemes see here:
https://github.com/ehn-dcc-development/ehn-dcc-schema/compare/1.0.0...1.3.0

For a more detailed analysis of differences in schemes feel free to also look to here:
https://github.com/ehn-dcc-development/dgc-business-rules/issues/56#issuecomment-898033415

So, it's not only a QA/communication problem "TSI <-> test provider", but also a CWA problem.
For solving, it would likely need the collaboration of all, so I'm now also pinging
@mlenkeit (sorry...)

**Comment by vaubaehn** [comment]
CWA release 2.7 will get an update for the DCC JSON schema to 1.3.0... so probably from CWA 2.7 on these test DCCs should be validated without problem.
Related PR: https://github.com/corona-warn-app/cwa-app-android/pull/3874

However, it should be tested how schema changes for DCCs affect technical validation in CWA.
When looking to https://github.com/ehn-dcc-development/dgc-business-rules/issues/56#issuecomment-898033415, there should probably no problem in backwards compatibility (except: number of events allowed in DCC, country code for place of vaccination/test, value for type of test, length of NAA test name), as the changes may only affect a very small number of DCCs practically (but this is a guess, though).

One solution for the future could be, that CWA comes bundled with all availble DCC JSON schemes, reads the hcert and picks the provided scheme version out of it at first, then runs the technical validity check with required (bundled) schema.

**Comment by darkdragon-001** [comment]
> Hi, could you please provide as much details as possible, where you made the test?

I did the test at the test center with uuid `e5bdf3e2-fc59-11eb-9e23-0a580a833616` from https://map.schnelltestportal.de/ about half an hour before reporting the problem.

**Comment by vaubaehn** [comment]
@darkdragon-001 
Could you please provide the 'real name' of the test center and the city, and the day of the test, please?

**Comment by darkdragon-001** [comment]
@vaubaehn Can you please provide me a secure official e-mail address where I can submit such sensitive data? I am not disclosing this publicly...

**Comment by vaubaehn** [comment]
@darkdragon-001 
Although I'm quite careful with data privacy or sensitive information/data, I was not observing any problem here, as the test center offers its service to the public and its name/address are obviously publicly published at least in the map https://map.schnelltestportal.de/

Anyway, I'm respecting your wish for privacy anyway.

As I am not any developer here, I neither can provide you an official nor a secure address to submit these data.

You can now either wait, until any SAP official offers you to send these data via e-mail (it will likely be @thomasaugsten who will ask you to do so),
or you may try to find out, who is the software company working for that test center, and then contact them directly, and ask them for a temporary fix:
They will need to shorten their Test Center name in the field 'tc' for building the EU Digital Covid Certificates to a maximum of 50 characters. Unless they won't do so, it will apparently not be possible to import these certificates into Corona-Warn-App. Depending on the time, when a version of Corona-Warn-App will be released that is capable of validating DCCs with longer test center names, dozens to hundreds of users may be affected, depending on the scale of the test center.
For affected users it's extremly uncomfortable, when they need the test DCC for travelling... So it could be good to act fast.

Kind regards, v.

**Comment by dsarkar** [comment]
@darkdragon-001 Thanks for reporting. @vaubaehn Thanks for additional information and analysis. Internal Tracking ID: EXPOSUREAPP-8986

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@darkdragon-001 As @vaubaehn  pointed out already in his comment https://github.com/corona-warn-app/cwa-app-android/issues/3924#issuecomment-898499723 it should be possible to import that certificate with CWA 2.7. We can expect that CWA Version 2.7 will be rolled out very soon, I will ping you here again, once roll out started.

**Comment by dsarkar** [comment]
@darkdragon-001 Release 2.7 has been rolled out yesterday. It is a staged roll out, but you can trigger on iOS an update if go to the AppStore and search for the CWA. Can you confirm that you are able to import the certificate with CWA 2.7, please. Thanks, best wishes DS

**Comment by Ein-Tim** [comment]
@dsarkar 

I think @darkdragon-001 has an Android device 😉

**Comment by dsarkar** [comment]
@Ein-Tim Right! My bad ....

**Comment by darkdragon-001** [comment]
I just installed Version 2.7.1 on Android but there is still an error:
<details><pre>
de.rki.coronawarnapp.covidcertificate.common.exception.InvalidHealthCertificateException: Json schema invalid.

de.rki.coronawarnapp.covidcertificate.common.exception.InvalidHealthCertificateException: Json schema invalid.
	at de.rki.coronawarnapp.covidcertificate.common.certificate.DccV1Parser.checkSchema(DccV1Parser.kt:10)
	at de.rki.coronawarnapp.covidcertificate.common.certificate.DccV1Parser.parse(DccV1Parser.kt:9)
	at de.rki.coronawarnapp.covidcertificate.common.certificate.DccQrCodeExtractor.parse(DccQrCodeExtractor.kt:7)
	at de.rki.coronawarnapp.covidcertificate.common.certificate.DccQrCodeExtractor.extract(DccQrCodeExtractor.kt:13)
	at de.rki.coronawarnapp.covidcertificate.test.core.TestCertificateProcessor.obtainCertificate$Corona_Warn_App_deviceRelease(TestCertificateProcessor.kt:55)
	at de.rki.coronawarnapp.covidcertificate.test.core.TestCertificateProcessor$obtainCertificate$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:11)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:3)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
Caused by: java.lang.IllegalArgumentException: Schema Validation did not pass:
$.t[0].tc: may only be 80 characters long
	at de.rki.coronawarnapp.covidcertificate.common.certificate.DccV1Parser.checkSchema(DccV1Parser.kt:9)
	... 12 more
</details></pre>

I also contacted the developer of the test center software with a link to this issue.

**Comment by vaubaehn** [comment]
@mtwalli 
Quick question: can the exception displayed above also occur, when field tc is `null` (but error text is not covering this condition)?
Fast response would be appreciated to give test center (developer who may have a look here) the right solution.

To all: 80 characters for a test center name is quite long and unrealistic...

**Comment by dsarkar** [comment]
@darkdragon-001 Thanks for the feedback. Info is forwarded internally.
