### ISSUE TITLE
0.8.9 crashes

### ISSUE THREAD

**Issue by icrf2000** [corona-warn-app/cwa-app-android#411]
App crashes when clicking "NEXT" on the "Data Privacy" screen. Device is Galaxy S10, Android 10. The line "Nearby.EXPOSURE_NOTIFICATION_API is not available on this device." in the trace is strange, the API IS installed.

```2020-06-12 11:51:08.003 31227-31227/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.rki.coronawarnapp, PID: 31227
    m0.b.a.a.c.k.b: 17: API: Nearby.EXPOSURE_NOTIFICATION_API is not available on this device. Connection failed with: a{statusCode=UNKNOWN_ERROR_CODE(39507), resolution=null, message=null}
        at m0.b.a.a.c.k.l.f0.b(com.google.android.gms:play-services-base@@17.3.0:4)
        at m0.b.a.a.c.k.l.e$a.e(com.google.android.gms:play-services-base@@17.3.0:8)
        at m0.b.a.a.c.k.l.e$a.d(com.google.android.gms:play-services-base@@17.3.0:50)
        at m0.b.a.a.c.k.l.e$a.l(com.google.android.gms:play-services-base@@17.3.0:1)
        at m0.b.a.a.c.l.b$k.c(com.google.android.gms:play-services-basement@@17.3.0:4)
        at m0.b.a.a.c.l.b$f.a(com.google.android.gms:play-services-basement@@17.3.0:7)
        at m0.b.a.a.c.l.b$g.handleMessage(com.google.android.gms:play-services-basement@@17.3.0:52)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at m0.b.a.a.e.b.d.dispatchMessage(com.google.android.gms:play-services-basement@@17.3.0:1)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2020-06-12 11:51:08.007 5874-6826/? W/ActivityManager: crash : de.rki.coronawarnapp,0
2020-06-12 11:51:08.008 5874-6826/? W/ActivityTaskManager:   Force finishing activity de.rki.coronawarnapp/.ui.onboarding.OnboardingActivity```

**Comment by jakobmoellersap** [comment]
please retry with 0.8.17

**Comment by icrf2000** [comment]
Better, doesn't crash anymore with 0.8.17. But gives another error popup now. Unfortunately I cannot take a screenshot. Says something like

CAUSE: 9002, Something went wrong
17: API:
Nearby.EXPOSURE_NOTIFICATION_API is not available on this device. Which I think isn't true:

![device-2020-06-12-121139](https://user-images.githubusercontent.com/11777822/84493315-da49b180-aca7-11ea-96c3-8f306a9bf5f7.png)

**Comment by pwoessner** [comment]
Hi @icrf2000 , the issue is mostly caused by the fact that the apk you are using is not officially signed and therefore the app is not allowed to access the tracing API.

**Comment by icrf2000** [comment]
Ok, understood, thanks for the feedback. Good luck for the go-live!
