### ISSUE TITLE
Error during certificate retrieval with wrong date

### ISSUE THREAD

**Issue by Huber1** [corona-warn-app/cwa-app-android#4689]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3a (sargo)
- Android version: 12 (Build number SQ1A.220105.002)
- App version: 2.15.1

## Describe the bug

When adding a Test (in my case PCR) and unintentionally setting the wrong birth date, the app shows the result on the home page, but the qr-code in the certificate tab is not shown. Instead there's an 'Error during certificate retrieval'.
A tap on the try again button->details shows following exceptions:

```
de.rki.coronawarnapp.covidcertificate.common.exception.TestCertificateException: Public Key Registration failed with 403: Registration token is not allowed to issue a DCC.

de.rki.coronawarnapp.covidcertificate.common.exception.TestCertificateException: Public Key Registration failed with 403: Registration token is not allowed to issue a DCC.
	at de.rki.coronawarnapp.covidcertificate.test.core.server.TestCertificateServer$registerPublicKeyForTest$2.invokeSuspend(TestCertificateServer.kt:21)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:17)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
Caused by: de.rki.coronawarnapp.exception.http.ForbiddenException: Error during web request: code=403 message= body='
	at de.rki.coronawarnapp.http.HttpErrorParser.intercept(HttpErrorParser.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
	at de.rki.coronawarnapp.http.interceptor.RetryInterceptor.intercept(RetryInterceptor.kt:3)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:5)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
	at de.rki.coronawarnapp.http.interceptor.WebSecurityVerificationInterceptor.intercept(WebSecurityVerificationInterceptor.kt:3)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:25)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:12)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
```

## Steps to reproduce the issue

1. Scan test qr-code
2. set a wrong birth date
3. wait for test result
4. See error on certificates tab

## Expected behaviour

qr-code with test result shows up or a possibility to set the correct date afterwards

## Additional context

I got the wrong date because my system language is english but the country is german. i typed in the date in the german format so day and month are changed.

---
Internal Tracking ID: [EXPOSUREAPP-11419](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11419)

**Comment by larswmh** [comment]
Thanks for your report @Huber1. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11419](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11419)

---
Corona-Warn-App Open Source Team

**Comment by Huber1** [comment]
Is there any update on this topic yet?

**Comment by mtwalli** [comment]
@Huber1  Changing the date of birth is not possible with the current architecture. This would require a larger change on the server-side and re-evaluating the security implications.
