### ISSUE TITLE
"A TAN for submission could not be generated" when trying to warn others

### ISSUE THREAD

**Issue by FrederikP** [corona-warn-app/cwa-app-android#5248]
## Avoid duplicates
* [ x ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ x ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ x ] Bug is not already reported in another issue

## Technical details

- Device name: Pocofone F1
- Android version: 11 
- App version: 2.22.1

## Describe the bug

I cannot warn others about a positive test result. There is an error message. It happens again and again, when retrying.

## Steps to reproduce the issue

1. successfully import positive rapid test result
2. Click "Warn others"
3. Accept
4. Enter Symptoms
5. Yes
6. Next
7. Choose yesterday
8. -> Error is displayed: "Error - A TAN for submission could not be generated. Please contact the technical hotline via App Information -> Technical Hotline"
9. I can click on Details and it shows me a stack trace involving a 400 http response. 
10. click OK
11. It says Thank you, but probably didn't work. I can repeat this starting with step 2 with the same result

![image](https://user-images.githubusercontent.com/483596/171163526-6ef9ce8c-7828-44ac-a5b8-dfd67d452c5b.png)
![image](https://user-images.githubusercontent.com/483596/171163544-d1024a18-21c9-4a86-a0eb-e259f4db0b63.png)

## Expected behaviour

There shouldn't be an error.

## Possible Fix

-

## Additional context

I didn'[t wanna call the hotline, because I'm really not feeling well and am not in the mood. Also I think these technical issues can better be handled in written form.

**Comment by FrederikP** [comment]
Full stack trace:

```
Cause:
de.rki.coronawarnapp.exception.TanPairingException: Tan has been retrieved before for this registration token
	at de.rki.coronawarnapp.playbook.DefaultPlaybook.submit(DefaultPlaybook.kt:29)
	at de.rki.coronawarnapp.playbook.DefaultPlaybook$submit$1.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
Caused by: de.rki.coronawarnapp.exception.http.BadRequestException: Error during web request: code=400 message= body='
	at de.rki.coronawarnapp.http.HttpErrorParser.intercept(HttpErrorParser.kt:36)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
	at de.rki.coronawarnapp.http.interceptor.RetryInterceptor.intercept(RetryInterceptor.kt:3)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:4)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
	at de.rki.coronawarnapp.http.interceptor.WebSecurityVerificationInterceptor.intercept(WebSecurityVerificationInterceptor.kt:3)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:25)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:12)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

**Comment by FrederikP** [comment]
Ah probably wasn't able to find it, because of German vs. English. Sorry about opening another one. Go ahead and merge them. Thanks for the quick response

**Comment by Ein-Tim** [comment]
I added https://github.com/corona-warn-app/cwa-app-android/issues/4815#issuecomment-1142022955. I think you can close this issue now, if @mlenkeit or @Thomasaugsten doesn't want e.g. an error log, or so.

**Comment by mlenkeit** [comment]
> Ah probably wasn't able to find it, because of German vs. English. Sorry about opening another one. Go ahead and merge them. Thanks for the quick response

@FrederikP did you happen to have error log activated before the error occurred? If so, it would be really helpful if you could share it.

**Comment by mlenkeit** [comment]
@FrederikP ... or do you happen to recall at what time of the day (approximately) you saw the error message?

**Comment by mlenkeit** [comment]
@FrederikP thanks for the quick response 👍
