### ISSUE TITLE
App will not open anymore

### ISSUE THREAD

**Issue by Cadenus** [corona-warn-app/cwa-app-android#578]
## Describe the bug

The app is not running in background nor can it be started up front after it worked yesterday. 
When trying to open the app, the following fatal exception can be seen in logcat:

`2020-06-17 09:27:25.508 603-1321/? D/SurfaceFlinger: try removeLayer layer name: <Splash Screen de.rki.coronawarnapp#0>, with topLevelOnly : 1
2020-06-17 09:27:25.908 16162-16162/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.rki.coronawarnapp, PID: 16162
    java.lang.SecurityException: Could not decrypt value. decryption failed
        at j0.w.a.a.b(EncryptedSharedPreferences.java:33)
        at j0.w.a.a.getBoolean(EncryptedSharedPreferences.java:1)
        at x.a.a.q.a.a(UpdateChecker.kt:23)
        at x.a.a.q.a$a.n(Unknown Source:11)
        at l0.n.k.a.a.e(ContinuationImpl.kt:2)
        at z.a.s0.run(DispatchedTask.kt:18)
        at android.os.Handler.handleCallback(Handler.java:809)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7383)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
     Caused by: java.security.GeneralSecurityException: decryption failed
        at k0.b.c.a.b0.b$b.b(AeadWrapper.java:15)
        at j0.w.a.a.b(EncryptedSharedPreferences.java:5)
        at j0.w.a.a.getBoolean(EncryptedSharedPreferences.java:1) 
        at x.a.a.q.a.a(UpdateChecker.kt:23) 
        at x.a.a.q.a$a.n(Unknown Source:11) 
        at l0.n.k.a.a.e(ContinuationImpl.kt:2) 
        at z.a.s0.run(DispatchedTask.kt:18) 
        at android.os.Handler.handleCallback(Handler.java:809) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7383) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963) 
2020-06-17 09:27:25.912 1034-6648/? W/ActivityManager:   Force finishing activity de.rki.coronawarnapp/.ui.LauncherActivity
2020-06-17 09:27:25.981 1034-1390/? W/InputDispatcher: channel 'ee7c0d7 de.rki.coronawarnapp/de.rki.coronawarnapp.ui.LauncherActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2020-06-17 09:27:25.981 1034-1390/? E/InputDispatcher: channel 'ee7c0d7 de.rki.coronawarnapp/de.rki.coronawarnapp.ui.LauncherActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
`

Stopping the app and restarting the phone does not work either.

## Expected behaviour

I can open the app.

## Steps to reproduce the issue

I don't know.

## Technical details

Huawei P20 (EML-L29, Android 8.1.0)

## Possible Fix

No idea. I don't know if reinstalling would solve the problem for me, but i guess the issue is that my id would then be another one?

## Additional context

I did not install new apps after the Corona Warn App, i cannot exclude automatic updates of other apps. No system update since yesterday.

**Comment by tomjschwanke** [comment]
This seems to be the same as #486, try to follow the steps there.

**Comment by Cadenus** [comment]
Thank you. That did the trick.

**Comment by rekire** [comment]
I've got the same crash now:
```
    --------- beginning of crash
2020-10-07 09:42:04.485 14909-14909/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.rki.coronawarnapp, PID: 14909
    java.lang.RuntimeException: Unable to create application de.rki.coronawarnapp.CoronaWarnApplication: java.lang.SecurityException: Could not decrypt value. decryption failed
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.SecurityException: Could not decrypt value. decryption failed
        at androidx.security.crypto.EncryptedSharedPreferences.getDecryptedObject(EncryptedSharedPreferences.java:33)
        at androidx.security.crypto.EncryptedSharedPreferences.getLong(EncryptedSharedPreferences.java:1)
        at de.rki.coronawarnapp.CoronaWarnApplication.onCreate(CoronaWarnApplication.kt:46)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.security.GeneralSecurityException: decryption failed
        at com.google.crypto.tink.aead.AeadWrapper$WrappedAead.decrypt(AeadWrapper.java:15)
        at androidx.security.crypto.EncryptedSharedPreferences.getDecryptedObject(EncryptedSharedPreferences.java:5)
        at androidx.security.crypto.EncryptedSharedPreferences.getLong(EncryptedSharedPreferences.java:1) 
        at de.rki.coronawarnapp.CoronaWarnApplication.onCreate(CoronaWarnApplication.kt:46) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

I'm just surprised that the line numbers do not match at all. I do not even find where that shared property is read.
