### ISSUE TITLE
Is it really possible to test the app? How to become whitelisted inside GMS?

### ISSUE THREAD

**Issue by gitbrueck** [corona-warn-app/cwa-app-android#95]
Known Issue: "The Exposure Notification API is gonna block you from successfully testing the Application unless you are whitelisted inside GMS."

**Comment by marcmuschko** [comment]
Dear @gitbrueck,

thank you for reaching out! 
Unfortunately this is not something we are able to help you with at the moment, as the authority of whitelisting Google accounts is not within the Android development realm. The general issue of testing the app end to end including the Exposure Notification API should be resolved in near future, as this topic is currently in clarification.
I will leave the issue open until it is resolved, the mentioned known issue will be removed from the list as well.

Best,
Marc

**Comment by tallinn1960** [comment]
Is the exception "com.google.android.gms.common.api.ApiException: 17: API: Nearby.EXPOSURE_NOTIFICATION_API is not available on this device. Connection failed with: ConnectionResult{statusCode=UNKNOWN_ERROR_CODE(39507), resolution=null, message=null}" an indication that one is not "whitelisted"?

**Comment by mh-** [comment]
@tallinn1960 Yes, that's the error message you get in this case. 
If you want to try out whether your Android device is capable of the service (i.e. if the correct Google Play Services are installed), you could try e.g. the officially published [app from Italy](https://play.google.com/store/apps/details?id=it.ministerodellasalute.immuni). Once such an app is officially published, it doesn't require whitelisting anymore.

**Comment by wolkenschieber** [comment]
To increase visibility to search engines, here is the corresponding stack trace:
```
W/System.err: com.google.android.gms.common.api.ApiException: 17: API: Nearby.EXPOSURE_NOTIFICATION_API is not available on this device. Connection failed with: ConnectionResult{statusCode=UNKNOWN_ERROR_CODE(39501), resolution=null, message=null}
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.2.1:4)
        at com.google.android.gms.common.api.internal.ApiExceptionMapper.getException(com.google.android.gms:play-services-base@@17.2.1:2)
        at com.google.android.gms.common.api.internal.zah.zaa(com.google.android.gms:play-services-base@@17.2.1:18)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(com.google.android.gms:play-services-base@@17.2.1:204)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zac(com.google.android.gms:play-services-base@@17.2.1:210)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(com.google.android.gms:play-services-base@@17.2.1:108)
        at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.onConnectionFailed(com.google.android.gms:play-services-base@@17.2.1:75)
        at com.google.android.gms.common.internal.zaf.onConnectionFailed(com.google.android.gms:play-services-base@@17.2.1:2)
W/System.err:     at com.google.android.gms.common.internal.BaseGmsClient$zzf.zza(com.google.android.gms:play-services-basement@@17.2.1:6)
        at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(com.google.android.gms:play-services-basement@@17.2.1:25)
        at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzo(com.google.android.gms:play-services-basement@@17.2.1:11)
        at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(com.google.android.gms:play-services-basement@@17.2.1:49)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at com.google.android.gms.internal.common.zzi.dispatchMessage(com.google.android.gms:play-services-basement@@17.2.1:8)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
E/ErrorReportReceiver: [EXPOSURENOTIFICATION]InternalExposureNotificationPermissionHelper 17: API: Nearby.EXPOSURE_NOTIFICATION_API is not available on this device. Connection failed with: ConnectionResult{statusCode=UNKNOWN_ERROR_CODE(39501), resolution=null, message=null}

```

**Comment by gitbrueck** [comment]
I installed Immuni officially published from Italy and it worked fine on my device.
Then I rebuild it from source and installed this.
Now I get a message box:
"Google Play Services isn't ready yet
Google Play Services is up to date but cannot enable
exposure notification yet.
Please try again later.

Error code: 39507
GOT IT"

It is not possible to test the sources without being whitelisted.

**Comment by corneliusroemer** [comment]
> @tallinn1960 Yes, that's the error message you get in this case.
> If you want to try out whether your Android device is capable of the service (i.e. if the correct Google Play Services are installed), you could try e.g. the officially published [app from Italy](https://play.google.com/store/apps/details?id=it.ministerodellasalute.immuni). Once such an app is officially published, it doesn't require whitelisting anymore.

Can you somehow accelerate the whitelisting, so that the app can be tested before being "officially" published. Surely, it's very counterproductive to not allow testers to test the app before it goes public - that's a recipe for failure.

**Comment by corneliusroemer** [comment]
I figured out a limited workaround, that allows you to at least have a peek at what happens after the onboarding process: Use an AVD (Android Virtual Device). It worked with my virtual Nexus 5X API 29. I could do the onboarding flow. I got app-internal warnings, that the Bluetooth API wasn't working, but that was all.

**Comment by mh-** [comment]
@corneliusroemer After uninstalling a previous build from my Android device, I could build a new version of the app that doesn't crash. (The crash on my device was related to database encryption, so I figured it's easiest to just delete the old database.) Of course, the app still doesn't connect to GMS API, because I'm not white-listed and I don't have the RKI/SAP signing keys.
But when it can't connect to the API, it doesn't crash, it just displays a message.

**Comment by corneliusroemer** [comment]
> @corneliusroemer After uninstalling a previous build from my Android device, I could build a new version of the app that doesn't crash. (The crash on my device was related to database encryption, so I figured it's easiest to just delete the old database.) Of course, the app still doesn't connect to GMS API, because I'm not white-listed and I don't have the RKI/SAP signing keys.
> But when it can't connect to the API, it doesn't crash, it just displays a message.

@mh- Cool! What did you change to make it not crash? I'm failing to get it to not crash.

@marcmuschko Since you said that the whitelisting problem should be resolved in the near future 6 days have passed. It's now being announced that the app will go live next week. When can we expect the whitelisting issue to be resolved? Saying "not within the Android development realm" isn't good. Please escalate with whomever can do something about this. Otherwise much of the PR is just hot air.

**Comment by mh-** [comment]
> @mh- Cool! What did you change to make it not crash? I'm failing to get it to not crash.

**Uninstall on device.** git pull. Build. Install again. No crash anymore.
